server:
  port: 8082

spring:
  application:
    name: customer-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cdsp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.sxxh.cdsp.po